# Состояния для создания/редактирования значка
BADGE_NAME = 1
BADGE_DESC = 2
BADGE_YEAR = 3
BADGE_MATERIAL = 4
BADGE_CONDITION = 5
BADGE_TAGS = 6
BADGE_PHOTOS = 7

EDIT_CHOICE = 10
EDIT_NAME = 11
EDIT_DESC = 12
EDIT_YEAR = 13
EDIT_MATERIAL = 14
EDIT_CONDITION = 15
EDIT_TAGS = 16